# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
stages:
  - test
  - deploy

pages: 
    image: debian:bullseye
    stage: deploy
    script:
        - mkdir -p public
        - cp *.html public/
    artifacts:
        paths:
            - public

htmlhint:
    stage: test
    tags:
        - shell
    script:
        - npx htmlhint *.html


lintcss:
    image: node:12
    stage: test
    tags:
        - docker
    script:
        - npm install csslint-cli
        - npx csslint-cli *.css > css_report.txt
    artifacts:
        paths:
            - css_report.txt

bagdes:
    stage: test
    tags:
        - shell
    script:
        - pip install anybadge
        - ~/.local/bin/anybadge --label=pipeline --value=passing --file=lint.svg passing=green failing=red
    artifacts:
        paths:
            - lint.svg
