# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
stages:
  - test
  - deploy

pages: 
    image: debian:bullseye
    stage: deploy
    script:
        - mkdir -p public
        - cp *.html public/
    artifacts:
        paths:
            - public

htmlhint:
    stage: test
    tags:
        - shell
    script:
        - npx htmlhint *.html


lintcss:
    stage: test
    tags:
        - shell
    script:
        - npm install csslint-cli
        - mkdir -p public
        - npx csslint-cli *.css > public/css_report.txt
    artifacts:
        paths:
            - public/css_report.txt
