# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
stages:
  - test
  - deploy

pages: 
    image: debian:bullseye
    stage: deploy
    script:
        - mkdir -p public
        - cp *.html public/
    artifacts:
        paths:
            - public

htmlhint:
    stage: test
    tags:
        - shell
    script:
        - npx htmlhint *.html


lintcss:
    image: node:12
    stage: test
    tags:
        - docker
    script:
        - npm install csslint-cli
        - npx csslint-cli *.css > css_report.txt
    artifacts:
        paths:
            - css_report.txt

bagdes:
    image: node:12
    stage: test
    tags:
        - docker
    script:
        - pip install anybadge
        - ~/.local/bin/anybadge -l pylint -v 2.22 -f lint.svg 2=red 4=orange 8=yellow 10=green
    artifacts:
        paths:
            - lint.svg
