# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages: 
    image: debian:bullseye
    script:
        - mkdir -p public
        - cp *.html public/
        - npx htmlhint *.html
    artifacts:
        paths:
            - public
    stages:
        - test
        - deploy
