# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
stages:
  - test
  - deploy

variables:
    Username: Moi
pages: 
    image: debian:bullseye
    stage: deploy
    script:
        - mkdir -p public
        - cp *.html public/
    artifacts:
        paths:
            - public

htmlhint:
    image: node:12
    stage: test
    script:
        - npx htmlhint *.html


lintcss:
    stage: test
    tags:
        - shell
    script:
        - echo $USER
        - echo $HOME
        - echo "Je suis $Username et mon mdp est $Passowrd"
        - ls ..
        - csslint *.css > css_report.txt
    artifacts:
        paths:
            - public/css_report.txt
